/* ══════════════════ The English of every Hungarian string on screen ══════════════════

   Keyed by the Hungarian sentence itself — see lib/crm/lang.ts for why there
   are no invented key names. A string missing from here renders in Hungarian,
   which is a visible, reportable fault rather than a broken-looking one.

   Kept as one flat map on purpose. Grouping by screen would mean deciding
   which screen a shared phrase belongs to, and "Megnyitás" belongs to nine. */

export const EN: Record<string, string> = {
  'eddig': 'until',
  'Archiválod ezt a(z)': 'Archive',
  'leadet?': 'leads?',
  'Eltűnnek minden listából, számlálóból és riportból, és az automata levelek leállnak.': 'They leave every list, count and report, and their automated e-mails stop.',
  'Honnan': 'Source',
  'Archivált leadek': 'Archived leads',
  'Tábla nézet': 'Board view',
  '+ Új lead': '+ Add lead',
  'CSV letöltés': 'Export CSV',
  'Vissza a leadekhez': 'Back to leads',
  'Archívum': 'Archive',
  'Név, e-mail, telefon, lakás…': 'Name, e-mail, phone, unit…',
  'Szűrés fázisra': 'Filter by stage',
  'Minden fázis': 'All stages',
  'Szűrés pontszámra': 'Filter by score',
  'Minden pontszám': 'All scores',
  'Szűrés értékesítőre': 'Filter by salesperson',
  'Szűrés forrásra': 'Filter by source',
  'Minden forrás': 'All sources',
  'Szűrés országra': 'Filter by country',
  'Minden ország': 'All countries',
  'Szűrés vásárlási időtávra': 'Filter by timeframe',
  'Bármelyik időtáv': 'Any timeframe',
  'Kerettől…': 'Budget from…',
  'Minimális keret': 'Minimum budget',
  'A keret pénzneme': 'Budget currency',
  'Szűrés arra, mi igényel figyelmet': 'Filter by what needs attention',
  'Bármilyen állapot': 'Any state',
  'Szűrés': 'Filter',
  '← Előző': '← Previous',
  'Következő →': 'Next →',
  'Ez a hónap': 'This month',
  'Semmi nem vész el — bármelyik visszaállítható.': 'Nothing is lost — each one can be restored.',
  'Archiválás': 'Archive',
  'Törlés': 'Delete',
  'Nincs a szűrőknek megfelelő lead.': 'No leads match these filters.',
  'Mind kijelölése': 'Select all',
  'Név': 'Name',
  'Érdeklődés': 'Enquiry',
  'Fázis': 'Stage',
  'Következő lépés': 'Next step',
  'Beérkezett': 'Received',
  'lead': 'lead',
  'oldal': 'page',
  '2 hét múlva': 'in 2 weeks',
  '3 nap múlva': 'in 3 days',
  'A fázisában ül a megengedett időn túl': 'Sitting in this stage past its threshold',
  'A fázisában ül a megengedett időn túl.': 'Sitting in the same stage past its threshold.',
  'A jóváhagyás a tulajdonos joga — te látod, de nem te döntesz.': 'Approval is the owner’s. You can see these; you do not decide them.',
  'Amit mára időzítettél.': 'Scheduled for today.',
  'Amíg valaki nem mond igent vagy nemet, addig a válasz egyik sem.': 'Until somebody says yes or no, the answer is neither.',
  'Az adásvételi kiment, véleményezés alatt van, vagy alá van írva.': 'The SPA is out, under review, or signed.',
  'Az egész csapat': 'Whole team',
  'Az én leadjeim': 'My leads',
  'Az építkezés haladására vár': 'Waiting on construction progress',
  'Bemutató': 'Presentation',
  'Betűméret': 'Text size',
  'Biztonság': 'Security',
  'Csak olvas': 'View only',
  'Döntést igényel': 'Needs a decision',
  'Egy követés, amit megígértél magadnak, és letelt a határideje.': 'A follow-up you promised yourself, past its date.',
  'Egy lakás a nevén van.': 'A unit is held for them.',
  'Egyéb': 'Other',
  'Eladva.': 'Sold.',
  'Elhallgatott': 'Gone quiet',
  'Ellentmondás': 'Contradiction',
  'Elveszett': 'Lost',
  'Extra kérés': 'Extra request',
  'Ez nem jött össze. Indokot kér.': 'Not this one. Needs a reason.',
  'Ezeket egy dátumig félretetted, és a dátum megjött.': 'You parked these until a date, and the date has come.',
  'Fizetések': 'Payments',
  'Forrásra vár': 'Waiting on funds',
  'Forró': 'Hot',
  'Félretéve': 'Parked',
  'Hideg': 'Cold',
  'Hogyan működik?': 'How it works',
  'Jegyzetek': 'Notes',
  'Kapcsolatban': 'Contacted',
  'Keresés mindenben…': 'Search everything…',
  'Kezdőlap': 'Home',
  'Kilépés': 'Sign out',
  'Kinek a leadjei': 'Whose leads',
  'Kiosztás': 'Allocation',
  'Kisebb betű': 'Smaller text',
  'Konkrét lakásról, árról és feltételekről beszéltek.': 'Talking about a specific unit, a price and terms.',
  'Követés': 'Follow up',
  'Követés…': 'Follow up…',
  'Leadek': 'Leads',
  'Lefoglalva': 'Reserved',
  'Legnagyobb betű': 'Largest text',
  'Lejárt': 'Late',
  'Lejárt foglalás': 'Lapsed reservation',
  'Látta: a helyszínen vagy élő videós körbevezetésen.': 'They have seen it — on site, or a live video walkthrough.',
  'Ma érkezett': 'Came in today',
  'Mai teendők': 'Today',
  'Marketing': 'Marketing',
  'Masterplan': 'Masterplan',
  'Megnyitás': 'Open',
  'Megnézte': 'Visit',
  'Megvette': 'Won',
  'Megérkezett. Még senki nem beszélt vele.': 'Arrived. Nobody has spoken to them yet.',
  'Meleg': 'Warm',
  'Mindenki': 'Everyone',
  'Minősítve': 'Qualified',
  'Munka': 'Work',
  'Mutasd': 'Show',
  'Mára tervezve': 'Due today',
  'Még senki nem beszélt velük': 'Nobody has spoken to them yet',
  'Nagyobb betű': 'Larger text',
  'Naptár': 'Calendar',
  'Nem mozdul': 'Not moving',
  'Nincs betervezve': 'Nothing planned',
  'Nincs következő lépés': 'No next step',
  'Nyelv': 'Language',
  'Névtelen': 'Unknown',
  'Partner döntésére vár': 'Needs a partner’s decision',
  'Pontszám': 'Score',
  'Pénz és papír': 'Money and paperwork',
  'Pénzügy': 'Finance',
  'Riportok': 'Reports',
  'Sales vezető': 'Head of sales',
  'Semmi nem vár rád.': 'Nothing is waiting.',
  'Semmi nem vár rád. Minden élő leaddel beszéltek, és mindegyiknek van dátumozott következő lépése.': 'Nothing is waiting. Every live lead has been spoken to and has a next step with a date on it.',
  'Szerződés': 'Contract',
  'Thaiföldi útra vár': 'Waiting on a trip to Thailand',
  'Tudjuk a keretet, a határidőt, hogy mire kell és honnan a pénz.': 'We know the budget, the timeframe, what it is for and where the money comes from.',
  'Tulajdonos': 'Owner',
  'Tárgyalás': 'Negotiation',
  'Vezetői': 'Management',
  'Visszatért a félretettekből': 'Back from nurture',
  'Volt bemutató vagy Zoom — ténylegesen megtörtént.': 'A presentation or Zoom has actually taken place.',
  'Volt egy valódi beszélgetés.': 'A real conversation has happened.',
  'Vásárol, de nem idén': 'Buying, but not this year',
  'a listában →': 'in the list →',
  'az egész csapatnál': 'across the whole team',
  'egy hét múlva': 'in a week',
  'holnap': 'tomorrow',
  'honnan a pénz': 'cash or financing',
  'keret': 'budget',
  'kérdés vár döntésre': 'waiting on a decision',
  'lead vár tőled valamit': 'leads want something from you',
  'ma': 'today',
  'ma jött vissza': 'due back today',
  'melyik lakás': 'residence of interest',
  'mikorra': 'timeframe',
  'mire kell': 'purpose',
  'napja': 'days ago',
  'napja nincs válasz': 'days with no reply',
  'napja visszatért': 'days ago',
  'napja vár': 'days waiting',
  'Élő üzletek, amikkel senki nem döntötte el, mi legyen.': 'Live deals nobody has decided what to do with.',
  'Értékesítő': 'Sales',
  'Összes lead →': 'All leads →',
  'Új': 'New',
  'Új leadek, akikkel még nem volt beszélgetés. Mindig ezek az elsők.': 'New leads with no conversation on record. These first, always.',
  'Ügynökségek': 'Agencies',
  'Ügynökségi vita': 'Competing agencies',
  '— az egész csapatnál.': ' — across the whole team.',
};
